name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker buildx build --platform linux/arm64 -t koreadersync:tag --output type=docker,dest=image.tar .

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v2
        with:
          name: docker-image
          path: image.tar
